# Generated by Django 2.1.1 on 2018-10-13 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=256, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '部门表',
                'verbose_name_plural': '部门表',
                'db_table': 'ugw_dept',
            },
        ),
        migrations.CreateModel(
            name='Diff_pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='上一张图片')),
            ],
            options={
                'verbose_name': '上照照片记录表',
                'verbose_name_plural': '上张照片记录表',
                'db_table': 'ugw_diff_pic',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='机器名')),
                ('ip', models.GenericIPAddressField(verbose_name='ip地址')),
                ('host_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='主机信息')),
                ('mac_addr', models.CharField(blank=True, max_length=128, null=True, verbose_name='物理地址')),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
                'db_table': 'ugw_host',
            },
        ),
        migrations.CreateModel(
            name='IMages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(max_length=128, verbose_name='图片物理存放位置')),
                ('size', models.IntegerField(verbose_name='图片文件大小')),
                ('length', models.IntegerField(verbose_name='图片分辨率之长')),
                ('width', models.IntegerField(verbose_name='图片分辨率之宽')),
                ('create_at', models.DateTimeField(verbose_name='图片创建时间')),
                ('desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注信息')),
                ('asb_path', models.FilePathField(max_length=256, verbose_name='绝对路径')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Host', to='DB_server.Host')),
            ],
            options={
                'verbose_name': '图片信息',
                'verbose_name_plural': '图片信息',
                'db_table': 'ugw_images',
            },
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='操作类型')),
                ('info', models.CharField(max_length=256, verbose_name='操作内容')),
                ('create_at', models.DateTimeField(verbose_name='操作时间')),
                ('host', models.ForeignKey(on_delete=None, related_name='logging', to='DB_server.Host')),
            ],
            options={
                'verbose_name': '日志信息',
                'verbose_name_plural': '日志信息',
                'db_table': 'ugw_log',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=128, verbose_name='路由别名')),
                ('url', models.URLField(max_length=128, verbose_name='页面路由')),
                ('top', models.CharField(max_length=128, verbose_name='顶级菜单')),
                ('child', models.CharField(max_length=32, verbose_name='子菜单')),
            ],
            options={
                'verbose_name': '路由菜单表',
                'verbose_name_plural': '路由菜单表',
                'db_table': 'ugw_menu',
            },
        ),
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=None, related_name='group', to='auth.Group', verbose_name='组权限id')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=None, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户权限id')),
            ],
            options={
                'verbose_name': '访问权限表',
                'verbose_name_plural': '访问权限表',
                'db_table': 'ugw_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=32, verbose_name='角色类型')),
                ('menu_id', models.ForeignKey(on_delete=None, related_name='menu', to='DB_server.Menu')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
                'db_table': 'ugw_role',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.CharField(max_length=128, unique=True, verbose_name='员工号')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名')),
                ('dept', models.CharField(blank=True, max_length=128, null=True, verbose_name='部门')),
                ('create_at', models.DateTimeField(verbose_name='创建时间')),
                ('desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'db_table': 'ugw_staff',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.CharField(max_length=256, unique=True, verbose_name='视频存放位置')),
                ('stat', models.CharField(choices=[('generated', '正在生成'), ('created', '生成完毕'), ('null', '没有报告')], max_length=256, verbose_name='视频状态')),
                ('url', models.URLField(blank=True, null=True, verbose_name='访问URL地址')),
                ('start_at', models.DateTimeField(verbose_name='视频开始时间')),
                ('end_at', models.DateTimeField(verbose_name='视频结束时间')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='DB_server.Host')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='DB_server.Staff')),
            ],
            options={
                'verbose_name': '视频信息',
                'verbose_name_plural': '视频信息',
                'db_table': 'ugw_video',
            },
        ),
        migrations.AddField(
            model_name='logging',
            name='user',
            field=models.ForeignKey(on_delete=None, related_name='logging', to='DB_server.Staff'),
        ),
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='DB_server.Staff'),
        ),
        migrations.AddField(
            model_name='diff_pic',
            name='host',
            field=models.ForeignKey(on_delete=None, related_name='host_id', to='DB_server.Host'),
        ),
        migrations.AddField(
            model_name='diff_pic',
            name='path',
            field=models.ForeignKey(on_delete=None, related_name='image', to='DB_server.IMages'),
        ),
    ]
