# Generated by Django 2.1.1 on 2018-10-13 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_top',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='父及菜单'),
            preserve_default=False,
        ),
    ]
