# Generated by Django 2.1.1 on 2018-10-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0002_menu_is_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='child',
            field=models.CharField(max_length=32, null=True, verbose_name='子菜单'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_top',
            field=models.CharField(max_length=32, null=True, verbose_name='父及菜单'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='top',
            field=models.CharField(max_length=128, null=True, verbose_name='顶级菜单'),
        ),
    ]
