# Generated by Django 2.1.1 on 2018-10-13 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0003_auto_20181013_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='中文名字'),
            preserve_default=False,
        ),
    ]
