# Generated by Django 2.1.1 on 2018-10-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0004_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.URLField(max_length=128, null=True, verbose_name='页面路由'),
        ),
    ]
