# Generated by Django 2.1.1 on 2018-10-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0005_auto_20181013_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_top',
            field=models.SmallIntegerField(max_length=32, null=True, verbose_name='父及菜单'),
        ),
    ]
