# Generated by Django 2.1.1 on 2018-10-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0006_auto_20181014_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='info',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='主机参数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='主机类型'),
        ),
    ]
