# Generated by Django 2.1.1 on 2018-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0007_auto_20181016_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_top',
            field=models.SmallIntegerField(null=True, verbose_name='父及菜单'),
        ),
    ]
