# Generated by Django 2.1.1 on 2018-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0008_auto_20181016_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='asb_path',
            field=models.CharField(max_length=256, verbose_name='绝对路径'),
        ),
    ]
