# Generated by Django 2.1.1 on 2018-10-17 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0010_permission_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='图片名'),
            preserve_default=False,
        ),
    ]
