# Generated by Django 2.1.1 on 2018-10-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0011_images_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='create_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
