# Generated by Django 2.1.1 on 2018-10-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0012_auto_20181017_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='视频大小'),
        ),
    ]
