# Generated by Django 2.1.1 on 2018-10-17 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0015_auto_20181017_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='视频结束时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='DB_server.Host'),
        ),
        migrations.AlterField(
            model_name='video',
            name='start_at',
            field=models.DateTimeField(verbose_name='视频开始时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, verbose_name='访问URL地址'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='DB_server.Staff'),
            preserve_default=False,
        ),
    ]
