# Generated by Django 2.1.1 on 2018-10-18 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0016_auto_20181017_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diff_pic',
            name='host',
        ),
        migrations.RemoveField(
            model_name='diff_pic',
            name='path',
        ),
        migrations.DeleteModel(
            name='Diff_pic',
        ),
    ]
