# Generated by Django 2.1.1 on 2018-10-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0017_auto_20181018_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='create_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='创建者'),
        ),
    ]
