# Generated by Django 2.1.1 on 2018-10-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0019_auto_20181018_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mirror',
        ),
    ]
