# Generated by Django 2.1.1 on 2018-10-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0020_delete_mirror'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='创建时间')),
                ('pid', models.SmallIntegerField(verbose_name='pid号')),
                ('host', models.CharField(max_length=128, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '客户端pid信息',
                'verbose_name_plural': '客户端pid信息',
                'db_table': 'ugw_pid',
            },
        ),
    ]
