# Generated by Django 2.1.1 on 2018-10-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0021_mirror'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirror',
            name='path',
            field=models.FilePathField(default=12313, verbose_name='文件路径'),
            preserve_default=False,
        ),
    ]
