# Generated by Django 2.1.1 on 2018-10-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0022_mirror_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirror',
            name='name',
            field=models.CharField(default=12313, max_length=128, verbose_name='文件名'),
            preserve_default=False,
        ),
    ]
