# Generated by Django 2.1.1 on 2018-10-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_server', '0023_mirror_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirror',
            name='c_img',
            field=models.FilePathField(default=123, verbose_name='客户机图片路径'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mirror',
            name='c_pid',
            field=models.FilePathField(default=12, verbose_name='客户机Pid路径'),
            preserve_default=False,
        ),
    ]
